# Generated by Django 3.1.6 on 2021-05-14 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210514_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='username',
            field=models.CharField(default=False, max_length=30, unique=True, verbose_name='username'),
        ),
    ]
