# Generated by Django 3.1.6 on 2021-05-14 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210514_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='username',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
